language: node_js
node_js:
  - "8.2.1"

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version
  - node server.js
  
script:
  - node_modules/.bin/newman run Server/unit_test/Selfie.postman_collection.json
